#!/usr/bin/with-contenv sh

set -e

USER=${USER:-transmission}
PASSWORD=${PASSWORD:-transmission}

sed -i "s*USERNAME*${USER}*g" /var/transmission/config/settings.json
sed -i "s*PASSWORD*${PASSWORD}*g" /var/transmission/config/settings.json

exit 0 
