#!/usr/bin/with-contenv sh

set -e

SERVERNAME=${SERVERNAME:-localhost}
TLS=${TLS:-no}

if [ $TLS == "yes" ]; then
  if [ ! -d /etc/nginx/tls ]; then
    s6-echo "[i] Create tls folder"
    s6-mkdir /etc/nginx/tls
  fi
  if [ ! -f /etc/nginx/tls/nginx.pem ]; then
    s6-echo "[i] Create server certificate"
    mv /etc/nginx/nginx.pem /etc/nginx/tls/
    mv /etc/nginx/nginx.crt /etc/nginx/tls/
  fi
  mv /etc/nginx/localhost-ssl /etc/nginx/localhost.site
else
  s6-echo "[i] Use NGINX without TLS"
  s6-rmrf /etc/nginx/localhost-ssl /etc/nginx/nginx.pem /etc/nginx/nginx.crt
fi
sed -i "s*SERVERNAME*$SERVERNAME*g" /etc/nginx/localhost.site
