#!/usr/bin/with-contenv sh
set -e

s6-echo "[i] Verify that the webapps folder exists."
if [ ! -d /usr/share/webapps ]; then
  s6-mkdir /usr/share/webapps
  s6-envuidgid nginx s6-chown -U -- /usr/share/webapps
fi

if [ -f /usr/local/sbin/php_info_page ]; then
  /usr/local/sbin/php_info_page
fi

if [ ! -d /etc/nginx/sites-enabled ]; then
  s6-mkdir /etc/nginx/sites-enabled
  s6-envuidgid nginx s6-chown -U -- /etc/nginx/sites-enabled
fi

if ls /etc/nginx/sites-enabled/* > /dev/null 2>&1
then
  s6-echo "[i] Site(s) for NGINX found."
else
  s6-echo "[i] Create example site for NGINX."
  cp /etc/nginx/localhost.site /etc/nginx/sites-enabled/example.site
  s6-envuidgid nginx s6-chown -U -- /etc/nginx/sites-enabled/example.site
  s6-chmod 675 /etc/nginx/sites-enabled/example.site
fi

exit 0
