version: '2.1'

services:
  jabbergram:
    restart: always
    container_name: jabbergram
    hostname: jabbergram
    image: maxder/alpine-jabbergram:x86_64
    volumes:
    - /srv/docker/jabbergram/config:/etc/jabbergram
    environment:
    - JID=exampleJid@nope.org
    - JIDPASS=difficultPassword
    - MUC=exampleMuc@muc.nope.org
    - NICK=jabbergram
    - TOKEN=jabbergramBotTokken
    - GROUP=-10293943920
    - XMPPRESPONDING=true # When a user mentions bot’s nickname in chat, the bot will respond with a message
    - XMPPRESPONDINGMESSAGE=I am only a robot, \%s.
    - XMPPGREETING=true
    - XMPPGREETINGMESSAGE=Hello \%s,\n\nfor your information:\nin this room is a gateway to telegram active.
