#!/usr/bin/with-contenv sh

set -e

XDAYS=${XDAYS:-30}

echo "ssl-cert-check -a -d '/etc/tls' -q -x ${XDAYS} -e ${ROOTMAIL}" > /etc/periodic/daily/ssl-cert-check
chmod +x /etc/periodic/daily/ssl-cert-check

exit 0
