#!/usr/bin/with-contenv sh
set -e

JID=${JID:-exampleJid@nope.org}
JIDPASS=${JIDPASS:-difficultPassword}
MUC=${MUC:-exampleMuc@muc.nope.org}
NICK=${NICK:-jabbergram}
TOKEN=${TOKEN:-jabbergramBotToken}
GROUP=${GROUP:--10293943920}

if [ ! -f /etc/jabbergram/config.ini ]; then
  echo -e "[config]\njid = ${JID}\npassword = ${JIDPASS}\nmuc_room = ${MUC}\nnick = ${NICK}\ntoken = ${TOKEN}\ngroup = ${GROUP}" > /etc/jabbergram/config.ini
fi

exit 0
