#!/usr/bin/with-contenv sh
set -e

JID=${JID:-exampleJid@nope.org}
JIDPASS=${JIDPASS:-difficultPassword}
MUC=${MUC:-exampleMuc@muc.nope.org}
NICK=${NICK:-jabbergram}
TOKEN=${TOKEN:-jabbergramBotToken}
GROUP=${GROUP:--10293943920}
XMPPRESPONDING=${XMPPRESPONDING-true}
XMPPRESPONDINGMESSAGE=${XMPPRESPONDINGMESSAGE-I am a robot, \%s.}
XMPPGREETING=${XMPPGREETING-true}
XMPPGREETINGMESSAGE=${XMPPGREETINGMESSAGE-Hello \%s,\n\nfor your information:\nin this room is a gateway to telegram active.}

if [ ! -f /etc/jabbergram/config.ini ]; then
  echo -e "[config]\njid = ${JID}\npassword = ${JIDPASS}\nmuc_room = ${MUC}\nnick = ${NICK}\ntoken = ${TOKEN}\ngroup = ${GROUP}" > /etc/jabbergram/config.ini
fi

if [ ${XMPPRESPONDING} = "true" ]; then
  sed -i "s*self.bot.sendMessage(tg_group, text=message)*self.bot.sendMessage(tg_group, text=message)\n\n        if msg['mucnick'] != self.nick and self.nick in msg['body']:\n            self.send_message(mto=msg['from'].bare,\n                mbody=\"${XMPPRESPONDINGMESSAGE} \" % msg['mucnick'],\n                mtype='groupchat')*g" /usr/bin/jabbergram.py
fi

if [ ${XMPPGREETING} = "true" ]; then
  sed -i "s*self.xmpp_users\[muc\] = \[presence\['muc'\]\['nick'\]\]*self.xmpp_users\[muc\] = \[presence\['muc'\]\['nick'\]\]\n\n        if presence\['muc'\]\['nick'\] != self.nick:\n            self.send_message(mto=presence\['from'\].bare,\n                mbody=\"${XMPPGREETINGMESSAGE}\" % (presence\['muc'\]\['nick'\]),\n                mtype='groupchat')*g" /usr/bin/jabbergram.py
fi

rm /etc/cont-init.d/01-firstrun

exit 0
