#!/usr/bin/with-contenv sh
set -e

JID=${JID:-exampleJid@nope.org}
JIDPASS=${JIDPASS:-difficultPassword}
MUC=${MUC:-exampleMuc@muc.nope.org}
NICK=${NICK:-jabbergram}
TOKEN=${TOKEN:-jabbergramBotToken}
GROUP=${GROUP:--10293943920}
RESPONDING=${RESPONDING-true}
RESPONDINGMESSAGE=${RESPONDINGMESSAGE-I am a robot, \%s.}

if [ ! -f /etc/jabbergram/config.ini ]; then
  echo -e "[config]\njid = ${JID}\npassword = ${JIDPASS}\nmuc_room = ${MUC}\nnick = ${NICK}\ntoken = ${TOKEN}\ngroup = ${GROUP}" > /etc/jabbergram/config.ini
fi

if [ ${RESPONDING} = "true" ]; then
  sed -i "s*self.bot.sendMessage(tg_group, text=message)*self.bot.sendMessage(tg_group, text=message)\n\n        if msg['mucnick'] != self.nick and self.nick in msg['body']:\n            self.send_message(mto=msg['from'].bare,\n                mbody=\"${RESPONDINGMESSAGE} \" % msg['mucnick'],\n                mtype='groupchat')*g" /usr/bin/jabbergram.py
fi

exit 0
