#!/usr/bin/with-contenv sh

set -e

if [ ! -d /etc/prosody/config ]; then
  mkdir /etc/prosody/config
fi

if find "/etc/prosody/config" -mindepth 1 -print | grep -q .; then
  echo -e "\n[i] Config found."
  mv /etc/prosody/prosody.cfg.lua /etc/prosody/orig.prosody.cfg.lua
  ln -s /etc/prosody/config/prosody.cfg.lua /etc/prosody/prosody.cfg.lua
else
  mv /etc/prosody/prosody.cfg.lua /etc/prosody/config/prosody.cfg.lua
  ln -s /etc/prosody/config/prosody.cfg.lua /etc/prosody/prosody.cfg.lua
fi

rm /etc/cont-init.d/02-firstrun
rm /usr/local/sbin/firstrun

exit 0
