#!/usr/bin/with-contenv sh
set -e

CHARSET=${CHARSET:-UTF-8}

if [ ! $CHARSET = "UTF-8" ]; then
  sed -i "s*default_charset = \"UTF-8\"*default_charset = \"$CHARSET\"*g" /etc/php/php.ini
fi

if [ ! -d "/tmp" ]; then 
  mkdir /tmp
  chmod 777 /tmp
fi

if [ -f /firstrun ]; then

  # Hiawatha
  if [ $(grep -c '^hiawatha:' /etc/passwd) == 1 ]; then
        s6-echo "[i] Webserver Hiawatha found."
        s6-echo "[i] Configure PHP."
	if [ -f /etc/php/php-fpm.conf ]; then
	  sed -i "s*user = nobody*user = hiawatha*g" /etc/php/php-fpm.conf
	  sed -i "s*group = nobody*group = www-data*g" /etc/php/php-fpm.conf
	fi
	if [ -f /etc/php/php-fpm.d/www.conf ]; then
	  sed -i "s*user = nobody*user = hiawatha*g" /etc/php/php-fpm.d/www.conf
	  sed -i "s*group = nobody*group = www-data*g" /etc/php/php-fpm.d/www.conf
	fi
	sed -i "s*\# DEFAULT WEBSITE*FastCGIserver \{\n        FastCGIid = PHP5\n        ConnectTo = 127.0.0.1:9000\n        Extension = php\n        SessionTimeout = 600\n\}\n\n\## DEFAULT WEBSITE*g" /etc/hiawatha/hiawatha.conf
	sed -i "s*\#CGIhandler = /usr/bin/php-cgi:php*CGIhandler = /usr/bin/php-cgi:php*g" /etc/hiawatha/hiawatha.conf
	sed -i "s*/var/log/hiawatha/error.log*/var/log/hiawatha/error.log \nExecuteCGI = yes\n*g" /etc/hiawatha/hiawatha.conf
	sed -i "s#/var/log/hiawatha/error.log#/var/log/hiawatha/error.log\n\#ReverseProxy ^/.* http://www.example.com:80/#g" /etc/hiawatha/hiawatha.conf
  	if [ -f "/fpm.conf" ]; then rm /fpm.conf ;fi
	if [ -d "/etc/nginx" ]; then rm -rf /etc/nginx ;fi
	find /etc/cont-init.d/ -type f -exec sed -i "s*nginx*hiawatha*g" {} \;
	chown hiawatha:www-data /tmp
  fi

  # NGINX
  if [ $(grep -c '^nginx:' /etc/passwd) == 1 ]; then
	s6-echo "[i] Webserver NGINX found."
	s6-echo "[i] Configure PHP."
	if [ -f /etc/php/php-fpm.conf ]; then
	  sed -i "s*user = nobody*user = nginx*g" /etc/php/php-fpm.conf
	  sed -i "s*group = nobody*group = www-data*g" /etc/php/php-fpm.conf
	fi
	if [ -d /etc/php7 ]; then
          sed -i "s*user = nobody*user = nginx*g" /etc/php/php-fpm.d/www.conf
          sed -i "s*group = nobody*group = www-data*g" /etc/php/php-fpm.d/www.conf
	fi
	sed -i "s*include /etc/nginx/headers.conf\;*include /etc/nginx/headers.conf\;\n        include /etc/nginx/fpm.conf\;\n\n        root /usr/share/webapps\;\nindex index.php\;*g" /etc/nginx/localhost.site
	mv /nginx_fpm.conf /etc/nginx/fpm.conf
	if [ -d "/etc/hiawatha" ]; then rm -rf /etc/hiawatha ;fi
	find /etc/cont-init.d/ -type f -exec sed -i "s*hiawatha*nginx*g" {} \;
        chown nginx:hiawatha /tmp
  fi

  rm /firstrun
fi

exit 0
