version: '3.5'

services:

  traefik:
    restart: always
    image: cms0/traefik
    container_name: lime-proxy
    ports:
     - 80:80
     - 443:443
     - 8080:8080
    networks:
     - external
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - traefik-config:/config/traefik

  mariadb:
    restart: unless-stopped
    container_name: lime-db
    hostname: DOCKER-lime-db
    image: linuxserver/mariadb
    volumes: 
     - lime-db:/config
    environment:
     - MYSQL_ROOT_PASSWORD=mysqlrootpasswd
    labels:
     - traefik.enable=false
    networks:
     - internal

  www:
    restart: unless-stopped
    container_name: lime-www
    hostname: DOCKER-lime-www
    image: cms0/httpd
    volumes: 
     - lime-www:/usr/local/apache2/htdocs
    links: 
     - lime:php-fpm
    labels:
     - "traefik.backend=lime"
     - "traefik.frontend.rule=Host:lime.docker.localhost"
     - "traefik.frontend.passHostHeader=true"
     - "traefik.frontend.entryPoints=https"
     - "traefik.frontend.redirect=https"
     - "traefik.protocol=http"
     - "traefik.port=80"
     - "traefik.docker.network=lime_external"
    networks:
     - internal
     - external

  lime:
    restart: unless-stopped
    image: cms0/limesurvey:3.15-php-fpm
    container_name: lime
    hostname: DOCKER-lime
    volumes: 
     - lime-www:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
    environment:
     - MYSQL_ROOT_PASSWORD=mysqlrootpasswd
     - SILENTINSTALL=yes
     - APPDIR=/usr/local/apache2/htdocs
    links: 
     - mariadb:mariadb
    depends_on: 
     - mariadb
    networks:
     - internal

volumes:
  lime-db:
    name: lime-db
  lime-www:
    name: lime-www
  traefik-config:
    name: traefik-config

networks:
  external:
    driver: bridge
    name: lime_external
  internal:
    external: false
    name: lime_internal
