FROM maxder/alpine-base:ARCHTAG
MAINTAINER Christian-Maxilian Steier

ARG GNU_LIBICONV_VERSION=1.15
ARG PHP_VERSION=5.6.31
ARG PHP_SHA256="6687ed2f09150b2ad6b3780ff89715891f83a9c331e69c90241ef699dec4c43f"

RUN BUILD_DEPS=" \
    tar \
    build-base \
    autoconf \
    automake \
    libtool \
    php5-dev \
    zlib-dev" \
 && apk -U add \
	${BUILD_DEPS} \
	php5-bcmath \
	php5-bz2 \
        php5-cgi \
        php5-cli \
        php5-common \
        php5-ctype \
	php5-curl \
	php5-dom \
	php5-exif \
	php5-fpm \
	php5-ftp \
        php5-gd \
        php5-gettext \
        php5-gmp \
	php5-imap \
	php5-intl \
        php5-json \
	php5-ldap \
        php5-mcrypt \
	php5-mssql \
	php5-mysqli \
	php5-opcache \
        php5-openssl \
        php5-odbc \
        php5-pcntl \
	php5-pdo \
	php5-pdo_dblib \
	php5-pdo_odbc \
	php5-pdo_pgsql \
        php5-pdo_sqlite \
        php5-pdo_mysql \
        php5-pear \
        php5-phar \
	php5-posix \
	php5-soap \
        php5-sqlite3 \
	php5-xml \
	php5-xmlreader \
	php5-xmlrpc \
        php5-zlib \
        php5-zip \
	gnu-libiconv@testing \
        curl

## libiconv
ADD https://ftp.gnu.org/pub/gnu/libiconv/libiconv-${GNU_LIBICONV_VERSION}.tar.gz /tmp/libiconv-${GNU_LIBICONV_VERSION}.tar.gz
ADD http://de2.php.net/get/php-${PHP_VERSION}.tar.gz/from/this/mirror /tmp/php-${PHP_VERSION}.tar.gz
RUN rm /usr/bin/iconv \
 && cd /tmp \
 && tar xzf libiconv-${GNU_LIBICONV_VERSION}.tar.gz \
 && cd libiconv-${GNU_LIBICONV_VERSION} \
 && ./configure --prefix=/usr/local \
 && make \
 && make install \
 && libtool --finish /usr/local/lib \
 && cd /tmp \
 && echo "Verifying integrity and authenticity..." \
 && echo "${PHP_SHA256}  php-${PHP_VERSION}.tar.gz" > php-${PHP_VERSION}.tar.gz.sha256 \
 && CHECKSUM_STATE=$(echo -n $(sha256sum -c php-${PHP_VERSION}.tar.gz.sha256) | tail -c 2) \
 && if [ "${CHECKSUM_STATE}" != "OK" ]; then echo "[!!] Checksum does not match!" && exit 1; fi \
 && tar xzf php-${PHP_VERSION}.tar.gz \
 && cd /tmp/php-5.*/ext/iconv \
 && phpize5 \
 && ./configure --with-iconv=/usr/lib --with-php-config=/usr/bin/php-config5 \
 && make \
 && cp modules/iconv.so /usr/lib/php5/modules \
 && echo "extension=iconv.so" > /etc/php5/conf.d/00_iconv.ini

## Small fixes
RUN ln -s /etc/php5 /etc/php \
 && ln -s /usr/bin/php5 /usr/bin/php \
 && ln -s /usr/lib/php5 /usr/lib/php \
 && ln -s /usr/bin/php-fpm5 /usr/bin/php-fpm

## PHP config
RUN sed -i -e "s*short_open_tag = Off*short_open_tag = On*g" /etc/php/php.ini \
 && sed -i -e "s*;always_populate_raw_post_data = -1*always_populate_raw_post_data = -1*g" /etc/php/php.ini

RUN echo "apc.shm_size = 128M" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.ttl=7200" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.user_ttl=7200" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.gc_ttl=3600" >> /etc/php/conf.d/apcu.ini

# Install composer global bin
RUN curl -sS https://getcomposer.org/installer | php \
 && mv composer.phar /usr/local/bin/composer

RUN rm -rf /var/cache/apk/*  /usr/share/* /var/cache/man/* /var/tmp \
 && touch /firstrun

COPY rootfs /
