FROM maxder/alpine-base:ARCHTAG
MAINTAINER Christian-Maxilian Steier

RUN apk -U --no-cache --no-progress add \
	php5-apcu \
	php5-bcmath \
	php5-bz2 \
        php5-cgi \
        php5-cli \
        php5-common \
        php5-ctype \
	php5-curl \
	php5-dom \
	php5-exif \
	php5-fpm \
	php5-ftp \
        php5-gd \
        php5-gettext \
        php5-gmp \
	php5-imap \
	php5-iconv \
	php5-intl \
        php5-json \
	php5-ldap \
        php5-mcrypt \
        php5-memcache \
	php5-mssql \
	php5-mysqli \
	php5-opcache \
        php5-openssl \
        php5-odbc \
	php5-pdo \
	php5-pdo_dblib \
	php5-pdo_odbc \
	php5-pdo_pgsql \
        php5-pdo_sqlite \
        php5-pdo_mysql \
        php5-pear \
        php5-phar \
	php5-posix \
	php5-soap \
        php5-sqlite3 \
        php5-xcache \
	php5-xml \
	php5-xmlreader \
	php5-xmlrpc \
        php5-zlib \
        php5-zip \
 && apk add -U --repository http://nl.alpinelinux.org/alpine/edge/testing/ --allow-untrusted phpredis

## PHP config
RUN sed -i -e "s/short_open_tag\s*=\s*Off/short_open_tag = On/g" /etc/php/php.ini \
 && sed -i -e "s/always_populate_raw_post_data\s*=\s*On/always_populate_raw_post_data = -1/g" /etc/php/php.ini

RUN echo "apc.shm_size = 128M" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.ttl=7200" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.user_ttl=7200" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.gc_ttl=3600" >> /etc/php/conf.d/apcu.ini
 
# Install composer global bin
RUN curl -sS https://getcomposer.org/installer | php \
 && mv composer.phar /usr/local/bin/composer

RUN rm -rf /var/cache/apk/*  /usr/share/doc /usr/share/man/ /usr/share/info/* /var/cache/man/* /var/tmp \
 && touch /firstrun

COPY rootfs /
EXPOSE 9000
