FROM maxder/alpine-base:ARCHTAG
MAINTAINER Christian-Maxilian Steier

ARG GNU_LIBICONV_VERSION=1.15
ARG PHP_VERSION=7.0.16
ARG PHP_SHA256="bc6709dc7612957d0533c09c9c8a9c2e7c4fd9d64e697707bb1b39670eab61d4"

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories
RUN BUILD_DEPS=" \
    tar \
    build-base \
    autoconf \
    automake \
    libtool \
    samba-dev \
    php7-dev \
    zlib-dev \
    git" \
 && apk -U add \
	${BUILD_DEPS} \
        file \
        icu-libs \
	libwebp \
	php7-apcu \
	php7-bcmath \
	php7-bz2 \
        php7-cgi \
        php7-common \
        php7-ctype \
	php7-curl \
	php7-dom \
	php7-exif \
	php7-fpm \
	php7-ftp \
        php7-gd \
        php7-gettext \
        php7-gmp \
	php7-imap \
	php7-iconv \
	php7-intl \
        php7-json \
	php7-ldap \
	php7-mbstring \
        php7-mcrypt \
        php7-memcached \
	php7-mysqli \
	php7-opcache \
        php7-openssl \
        php7-odbc \
        php7-pcntl \
	php7-pdo_dblib \
	php7-pdo_odbc \
        php7-pdo_sqlite \
        php7-pdo_mysql \
        php7-pear \
        php7-phar \
        php7-posix \
        php7-redis \
	php7-soap \
        php7-sqlite3 \
	php7-xml \
	php7-xmlreader \
	php7-xmlrpc \
        php7-zlib \
        php7-zip \
	curl

## PHP smbclient
RUN git clone git://github.com/eduardok/libsmbclient-php.git /tmp/smbclient \
 && cd /tmp/smbclient \
 && phpize7 \
 && ./configure --with-php-config=/usr/bin/php-config7 \
 && make \
 && make install \
 && echo "extension=smbclient.so" > /etc/php7/conf.d/00_smbclient.ini

## libiconv
ADD https://ftp.gnu.org/pub/gnu/libiconv/libiconv-${GNU_LIBICONV_VERSION}.tar.gz /tmp/libiconv-${GNU_LIBICONV_VERSION}.tar.gz
ADD http://de1.php.net/get/php-${PHP_VERSION}.tar.gz/from/this/mirror /tmp/php-${PHP_VERSION}.tar.gz
RUN cd /tmp \
 && tar xzf libiconv-${GNU_LIBICONV_VERSION}.tar.gz \
 && cd libiconv-${GNU_LIBICONV_VERSION} \
 && ./configure --prefix=/usr/local \
 && make \
 && make install \
 && libtool --finish /usr/local/lib \
 && cd /tmp \
 && echo "Verifying integrity and authenticity..." \
 && echo "${PHP_SHA256}  php-${PHP_VERSION}.tar.gz" > php-${PHP_VERSION}.tar.gz.sha256 \
 && CHECKSUM_STATE=$(echo -n $(sha256sum -c php-${PHP_VERSION}.tar.gz.sha256) | tail -c 2) \
 && if [ "${CHECKSUM_STATE}" != "OK" ]; then echo "[!!] Checksum does not match!" && exit 1; fi \
 && tar xzf php-${PHP_VERSION}.tar.gz \
 && cd /tmp/php-7.*/ext/iconv \
 && phpize7 \
 && ./configure --with-iconv=/usr/local --with-php-config=/usr/bin/php-config7 \
 && make \
 && cp modules/iconv.so /usr/lib/php7/modules \
 && echo "extension=iconv.so" > /etc/php7/conf.d/00_iconv.ini

## Small fixes
RUN ln -s /etc/php7 /etc/php \
 && ln -s /usr/sbin/php-fpm7 /usr/bin/php-fpm \
 && ln -s /usr/lib/php7 /usr/lib/php

## PHP config
RUN sed -i -e "s*short_open_tag = Off*short_open_tag = On*g" /etc/php/php.ini \
 && sed -i -e "s*;always_populate_raw_post_data = -1*always_populate_raw_post_data = -1*g" /etc/php/php.ini

RUN echo "apc.shm_size = 128M" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.ttl=7200" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.user_ttl=7200" >> /etc/php/conf.d/apcu.ini \
 && echo "apc.gc_ttl=3600" >> /etc/php/conf.d/apcu.ini
 
# Install composer global bin
RUN curl -sS https://getcomposer.org/installer | php \
 && mv composer.phar /usr/local/bin/composer

RUN apk del ${BUILD_DEPS} php7-pear php7-dev \
 && rm -rf /var/cache/apk/*  /usr/share/doc /usr/share/man/ /usr/share/info/* /var/cache/man/* /var/tmp \
 && touch /firstrun

COPY rootfs /
EXPOSE 9000
