#!/usr/bin/with-contenv sh

set -e

BOTNAME=${BOTNAME:-hello-world-bot}

if [ ! -d /bot/${BOTNAME} ]; then
  echo -e "[i] Initialize bot '${BOTNAME}' ... stay tuned!\n"
  mkdir -p /bot/${BOTNAME}
  cd /bot/${BOTNAME} 
  botpress init -y
  echo -e "\n"
fi


if [ -d /bot/${BOTNAME}/-y ]; then
  mv /bot/${BOTNAME}/-y /bot/${BOTNAME}2
  rm -rf /bot/${BOTNAME}
  mv /bot/${BOTNAME}2 /bot/${BOTNAME}
fi

sed -i "s*BOTNAME*${BOTNAME}*g" /etc/services.d/botpress/run

rm /etc/cont-init.d/firstrun
exit 0
