#!/usr/bin/with-contenv sh

set -e

DIR=$(dirname $(readlink -f "$0"))
DBHOST=${DBHOST:-db}
DBUSER=${DBUSER:-$DB_ENV_DBUSER}
DBPASS=${DBPASS:-$DB_ENV_DBPASS}

mysqldump  -u $DBUSER --password=$DBPASS --protocol=tcp -h $DBHOST --single-transaction --flush-logs --master-data=2 --all-databases | gzip > $DIR/db_backup.gz
echo 'purge master logs before date_sub(now(), interval 7 day);' | mysql -u $DBUSER --password=$DBPASS --protocol=tcp -h $DBHOST

exit 0
