#!/usr/bin/with-contenv sh
set -e

echo "[i] initialize MySQL data directory"

DBUSER=${DBUSER:-dbadmin}
DBPASS=${DBPASS:-dbadminpass}

if [ ! -d /var/lib/mysql/mysql ]; then
  mysql_install_db --user=mysql --datadir=/var/lib/mysql --rpm > /dev/null
  tfile=`mktemp`
  if [ ! -f "$tfile" ]; then
	return 1
  fi
  cat << EOF > $tfile
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.user where User = '';
DELETE FROM mysql.user WHERE user = '$DBUSER';
FLUSH PRIVILEGES;
CREATE USER '$DBUSER'@'127.0.0.1' IDENTIFIED BY '$DBPASS';
GRANT ALL PRIVILEGES ON *.* TO '$DBUSER'@'127.0.0.1' WITH GRANT OPTION;
CREATE USER '$DBUSER'@'%' IDENTIFIED BY '$DBPASS';
GRANT ALL PRIVILEGES ON *.* TO '$DBUSER'@'%' WITH GRANT OPTION;
EOF

  /usr/bin/mysqld --user=mysql --bootstrap --verbose=0 < $tfile
  rm -f $tfile
  echo -e " \n---\n[i] Connecting to the Database:\nmysql -u $DBUSER --password=$DBPASS --protocol=tcp\n---\n "

fi

# Tuning
if [ $(uname -m) == "armv6l" ] || [ $(uname -m) == "armv7l" ]; then
  sed -i 's/skip-external-locking/&\nquery_cache_size = 4M\ndefault-storage-engine = MyISAM/g' /etc/mysql/my.cnf 
fi
sed -i "s*#innodb_flush_log_at_trx_commit = 1*innodb_flush_log_at_trx_commit = 2*g" /etc/mysql/my.cnf

rm /etc/cont-init.d/01-firstrun

exit 0
