version: '3'

services:

  traefik:
    restart: always
    image: maxder/alpine-traefik.x86_64
    container_name: traefik
    ports:
     - 80:80
     - 443:443
    networks:
     - external
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /srv/docker/traefik:/config/traefik

  mariadb:
    restart: always
    container_name: mahara_db
    hostname: mahara_db
    image: linuxserver/mariadb
    volumes:
     - /srv/docker/mahara/db:/config
    environment:
     - MYSQL_ROOT_PASSWORD=rootpasswd
    labels:
     - traefik.enable=false
    networks:
     - internal

  elasticsearch:
    restart: always
    container_name: mahara_es
    hostname: mahara_es
    image: elasticsearch:5.5-alpine
    labels:
     - traefik.enable=false
    networks:
     - internal

  mahara:
    restart: always
    container_name: mahara
    hostname: mahara
    image: cms0/mahara:18.10-nginx
    volumes:
     - /srv/docker/mahara/config:/config
     - /srv/docker/mahara/data:/data
    environment:
     - MYSQL_ROOT_PASSWORD=rootpasswd
     - SERVERNAME=mahara.docker.localhost
     - TLS=no
     - SILENTINSTALL=yes ## Silent installation via CLI
     - APPADMINPASS=pwd123 ## Admin password for silent installation. Username is 'admin'
     - APPADMINEMAIL=admin@mydomain.org ## Admin email for silent insatllation
     #- APPFOLDER=portfolio ## Mahara in a subdir
     - ELASTICSEARCH_HOST=es
    links:
     - mariadb:db
     - elasticsearch:es
    labels:
     - "traefik.backend=mahara"
     - "traefik.frontend.rule=Host:mahara.docker.localhost"
     - "traefik.frontend.headers.customRequestHeaders=Host:mahara.docker.localhost"
     - "traefik.frontend.passHostHeader=true"
     - "traefik.frontend.entryPoints=http"
     - "traefik.protocol=http"
     - "traefik.port=80"
     - "traefik.docker.network=mahara_external"
    networks:
     - internal
     - external

networks:
  external:
    driver: bridge
  internal:
    external: false
