#!/usr/bin/with-contenv sh

set -e

ETHERPAD_PATH=/usr/share/webapps/etherpad
APPDB=${APPDB:-etherpad}
DBHOST=${DBHOST:-db}
DBUSER=${DBUSER:-etherpad}
DBPASS=${DBPASS:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 88 | head -n 1)}
ETHERPAD_TITLE=${ETHERPAD_TITLE:-Etherpad}
ETHERPAD_SESSION_KEY=${ETHERPAD_SESSION_KEY:-$(
                node -p "require('crypto').randomBytes(32).toString('hex')")}
ETHERPAD_ADMIN_USER=${ETHERPAD_ADMIN_USER:-admin}
ETHERPAD_ADMIN_PASS=${ETHERPAD_ADMIN_PASS-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)}
ETHERPAD_APIKEY=${ETHERPAD_APIKEY:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-$DB_ENV_MYSQL_ROOT_PASSWORD}
SILENTINSTALL=${SILENTINSTALL:-yes}

if [ ! -d /config/etherpad ]; then
  mkdir -p /config/etherpad
  chown abc:abc /config/etherpad
fi

if [ ! -f /config/etherpad/APIKEY.txt ]; then
 echo "$ETHERPAD_APIKEY" > /config/etherpad/APIKEY.txt
fi
s6-ln -s /config/etherpad/APIKEY.txt $ETHERPAD_PATH/APIKEY.txt


if [ $SILENTINSTALL == "yes" ]; then
  if [ -z 3306 ]; then
    echo >&2 'error: missing MYSQL_PORT_3306_TCP environment variable'
    echo >&2 '  Did you forget to --link some_mysql_container:db ?'
    exit 1
  fi
  until nc -z ${DBHOST} 3306; do sleep 1; echo "Waiting for DB to come up..."; done
  # Check if database already exists
  RESULT=`mysql -u root -p${MYSQL_ROOT_PASSWORD} \
  -h$DBHOST --skip-column-names \
  -e "SHOW DATABASES LIKE '${APPDB}'"`

  if [ "$RESULT" != $APPDB ]; then
    # mysql database does not exist, create it
    echo "Creating database ${APPDB}"
    mysql -u root --password=$MYSQL_ROOT_PASSWORD -h $DBHOST <<-EOF
    CREATE DATABASE IF NOT EXISTS ${APPDB} CHARACTER SET utf8mb4;
	GRANT ALL PRIVILEGES ON ${APPDB}.* TO '$DBUSER'@'%' IDENTIFIED BY '$DBPASS';
	FLUSH PRIVILEGES;
EOF
  fi
  if [ ! -f /config/etherpad/settings.json ]; then
    cat <<- EOF > /config/etherpad/settings.json
	{
	  "title": "$ETHERPAD_TITLE",
	  "ip": "0.0.0.0",
	  "port" :9001,
	  "dbType" : "mysql",
	  "dbSettings" : {
			    "user"    : "$DBUSER",
			    "host"    : "$DBHOST",
			    "password": "$DBPASS",
			    "database": "$APPDB"
			  },
	  "users": {
		    "$ETHERPAD_ADMIN_USER": {
		      "password": "$ETHERPAD_ADMIN_PASS",
		      "is_admin": true
		    }
	  },
	}
EOF
  fi
  if [ ! -f ${ETHERPAD_PATH}/settings.json ]; then
    s6-ln -s /config/etherpad/settings.json ${ETHERPAD_PATH}/settings.json
  fi
  echo -e "\n\n[i] Set automatic configuration:\n  APIKEY: $(cat ${ETHERPAD_PATH}/APIKEY.txt)\n  ADMIN: $ETHERPAD_ADMIN_USER\n  PASS: $ETHERPAD_ADMIN_PASS\n---\n"
fi

export

rm /etc/cont-init.d/40-install
exit 0
