#!/usr/bin/with-contenv sh

set -e

apk -U --no-progress add pwgen

WWWROOT=${WWWROOT:-/}
APPFOLDER=${APPFOLDER:-mahara}
APPDIR=/usr/share/webapps/${APPFOLDER}
APPDB=${APPDB:-mahara}
DBHOST=${DBHOST:-db}
DBUSER=${DBUSER:-$DB_ENV_DBUSER}
DBPASS=${DBPASS:-$DB_ENV_DBPASS}
APPADMIN=${APPADMIN:-admin}
APPADMINPASS=${APPADMINPASS:-pwd123}
APPADMINNAME=${APPADMINNAME:-Admin}
APPADMINEMAIL=${APPADMINEMAIL:-admin@mydomain.org}
APPSALD=${APPSALD:-$(pwgen -s -1 16)}
ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-127.0.0.1}
LANGUAGE=${LANGUAGE:-de}
INSTALL=${INSTALL:-silent}

if [ ${APPFOLDER} != "mahara" ]; then
  mv /usr/share/webapps/mahara /usr/share/webapps/${APPFOLDER}
  s6-rmrf /etc/nginx/sites-enabled/mahara.site
  s6-rename /etc/nginx/sites-enabled/subfolder /etc/nginx/sites-enabled/mahara.site
  sed -i "s*mahara*${APPFOLDER}*g" /etc/nginx/sites-enabled/mahara.site
else
  s6-rmrf /etc/nginx/sites-enabled/subfolder
fi

if [ ! -d /etc/mahara ]; then
  mkdir /etc/mahara
fi

if [ ! -f /etc/mahara/config.php ]; then
  cp -a ${APPDIR}/config-dist.php /etc/mahara/config.php
  sed -i "s|dbtype   = 'postgres'|dbtype   = 'mysql'|g" /etc/mahara/config.php
  sed -i "s|dbname   = ''|dbname   = '$APPDB'|g" /etc/mahara/config.php
  sed -i "s|dbuser   = ''|dbuser   = '$DBUSER'|g" /etc/mahara/config.php
  sed -i "s|dbpass   = ''|dbpass   = '$DBPASS'|g" /etc/mahara/config.php
  sed -i "s|dbhost   = 'localhost'|dbhost   = '$DBHOST'|g" /etc/mahara/config.php
  sed -i 's|\/\/ \$cfg->wwwroot|\$cfg->wwwroot|g' /etc/mahara/config.php
  sed -i "s|wwwroot = 'https:\/\/myhost.com\/mahara\/'|wwwroot = '$WWWROOT'|g" /etc/mahara/config.php
  sed -i "s|dataroot = '\/path\/to\/uploaddir'|dataroot = '\/data'|g" /etc/mahara/config.php
  sed -i 's|\/\/ \$cfg->passwordsaltmain|\$cfg->passwordsaltmain|g' /etc/mahara/config.php
  sed -i "s|passwordsaltmain = 'some long random string here with lots of characters'|passwordsaltmain = '$APPSALD'|g" /etc/mahara/config.php
  sed -i "s|emailcontact = ''|emailcontact = '$APPADMINEMAIL'|g" /etc/mahara/config.php
  sed -i "s#\/\/ closing php tag intentionally omitted to prevent whitespace issues#\$cfg->cleanurls = true;\n\$cfg->cleanurlinvalidcharacters = '/[^a-zA-Z0-9]+/';\n\$cfg->cleanurlvalidate = '/^[a-z0-9-]*\$/';\n\$cfg->cleanurlusereditable = true;\n\n\$cfg->log_dbg_targets     = LOG_TARGET_SCREEN | LOG_TARGET_ERRORLOG;\n\$cfg->log_info_targets    = LOG_TARGET_SCREEN | LOG_TARGET_ERRORLOG;\n\$cfg->log_warn_targets    = LOG_TARGET_SCREEN | LOG_TARGET_ERRORLOG;\n\$cfg->log_environ_targets = LOG_TARGET_SCREEN | LOG_TARGET_ERRORLOG;\n\n\$cfg->plugin_search_elasticsearch_host = '$ELASTICSEARCH_HOST';\n\n\/\/ closing php tag intentionally omitted to prevent whitespace issues#g" /etc/mahara/config.php
  s6-envuidgid nginx s6-chown -U -- /etc/mahara/config.php  
fi

if [ ! -f ${APPDIR}/config.php ]; then
  ln -s /etc/mahara/config.php ${APPDIR}/config.php
fi

## Language pack
cd /tmp/
if curl --output /dev/null --silent --head --fail "http://langpacks.mahara.org/${LANGUAGE}-MAHARA_VERSION_STABLE.tar.gz"; then
  wget http://langpacks.mahara.org/${LANGUAGE}-MAHARA_VERSION_STABLE.tar.gz
else
 wget http://langpacks.mahara.org/${LANGUAGE}-master.tar.gz
fi

if [ ! -d /data/langpacks  ]; then
  mkdir -p /data/langpacks
fi
tar -xvzf ${LANGUAGE}-* -C /data/langpacks/
s6-envuidgid nginx s6-chown -U -- /data/langpacks/${LANGUAGE}.utf8
rm -r /tmp/${LANGUAGE}*
echo " " && echo "---" && echo " "

if [ $INSTALL == "silent" ]; then
  until nc -z ${DBHOST} 3306; do sleep 1; echo "Waiting for DB to come up..."; done

  if ! mysql -u $DBUSER --password=$DBPASS -h $DBHOST -e "use ${APPDB}"; then
    echo -e "No database ${APPDB} found. Creating database now .."
    mysql -u $DBUSER --password=$DBPASS -h $DBHOST <<-EOF
    CREATE DATABASE IF NOT EXISTS ${APPDB} CHARACTER SET utf8 COLLATE utf8_unicode_ci;
    GRANT ALL PRIVILEGES ON ${APPDB}.* TO '$DBUSER'@'%' IDENTIFIED BY '$DBPASS';
    FLUSH PRIVILEGES;
EOF
    echo -e "\n---\nInstalling Mahara. Stay tuned!\n"
    s6-setuidgid nginx php ${APPDIR}/admin/cli/install.php --adminpassword='$APPADMINPASS' --adminemail=$APPADMINEMAIL
    echo -e "\n[i] Installed with \nUsername = $APPADMIN \nPassword = $APPADMINPASS \nEmail = $APPADMINEMAIL\n---\n"
  fi
fi  

apk del pwgen
rm /etc/cont-init.d/02-firstrun

exit 0
