version: '3.0'
services:
  mailpile:
    container_name: mailpile
    build: .
    image: mailpile
    volumes:
     - ./data:/root/.local/share/Mailpile
     - ./.gnupg:/root/.gnupg
     - /etc/localtime:/etc/localtime:ro
    ports:
     - 33411:33411
