#!/usr/bin/with-contenv sh
set -eu

ETHERPAD_PATH=/opt/etherpad
APPDB=${APPDB:-etherpad}
APPDBUSER=${DBUSER:-etherpad}
APPDBPASS=${DBPASS:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 88 | head -n 1)}
ETHERPAD_TITLE=${ETHERPAD_TITLE:-Etherpad}
ETHERPAD_SESSION_KEY=${ETHERPAD_SESSION_KEY:-$(
                node -p "require('crypto').randomBytes(32).toString('hex')")}
ETHERPAD_ADMIN_USER=${ETHERPAD_ADMIN_USER:-admin}
ETHERPAD_ADMIN_PASS=${ETHERPAD_ADMIN_PASS:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)}
ETHERPAD_DEFAULT_PADTEST=${ETHERPAD_DEFAULT_PADTEXT:-$(Welcome to Etherpad!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\n\nGet involved with Etherpad at http:\/\/etherpad.org\n)}
MYSQL_HOST=${MYSQL_HOST:-mariadb}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-}
SILENTINSTALL=${SILENTINSTALL:-no}

if [ $SILENTINSTALL = "yes" ]; then
  echo -e "\n[i] Silentinstall! Be patient :) \n"
  apk add -U --no-cache netcat-openbsd mariadb-client
  sleep 2
  if [ -z 3306 ]; then
    echo >&2 '[ERROR] missing MYSQL_PORT_3306_TCP environment variable'
    echo >&2 '  Did you forget to --link some_mysql_container:db ?'
    exit 1
  fi
  until nc -z ${MYSQL_HOST} 3306; do sleep 1; echo "Waiting for DB to come up..."; done
  # Check if database already exists
  RESULT=`mysql -u root -p${MYSQL_ROOT_PASSWORD} -h ${MYSQL_HOST} --skip-column-names \
  -e "SHOW DATABASES LIKE '${APPDB}'"`

  if [ "$RESULT" != $APPDB ]; then
    # mysql database does not exist, create it
    echo -e "[i] Creating database ${APPDB}"
    mysql -uroot --password=${MYSQL_ROOT_PASSWORD} -h ${MYSQL_HOST} <<-EOF
    CREATE DATABASE IF NOT EXISTS ${APPDB} CHARACTER SET utf8mb4;
    GRANT ALL PRIVILEGES ON ${APPDB}.* TO '${APPDBUSER}'@'%' IDENTIFIED BY '${APPDBPASS}';
    FLUSH PRIVILEGES;
EOF
  fi
  cat <<- EOF > /opt/etherpad/config/settings.json
	{
	  "title": "$ETHERPAD_TITLE",
	  "ip": "0.0.0.0",
	  "port" :9001,
	  "dbType" : "mysql",
	  "dbSettings" : {
			    "user"    : "${APPDBUSER}",
			    "host"    : "${MYSQL_HOST}",
			    "password": "${APPDBPASS}",
			    "database": "${APPDB}"
			  },
	  "users": {
		    "$ETHERPAD_ADMIN_USER": {
		      "password": "${ETHERPAD_ADMIN_PASS}",
		      "is_admin": true
		    }
	  },
	  "defaultPadText" : "$ETHERPAD_DEFAULT_PADTEXT",
	}
EOF
  s6-ln -s /opt/etherpad/config/settings.json /opt/etherpad/settings.json
  apk del --purge netcat-openbsd mariadb-client
  echo -e "\n\n[i] Set automatic configuration:\n  APIKEY: $(cat ${ETHERPAD_PATH}/APIKEY.txt)\n  ADMIN: $ETHERPAD_ADMIN_USER\n  PASS: $ETHERPAD_ADMIN_PASS\n---\n"
fi

# self-destruction
rm /etc/cont-init.d/20-install
exit 0
