#!/usr/bin/with-contenv sh

set -e

if [ "$(ls -A /usr/share/webapps/)" ]; then
  echo "[i] File(s) found in webapps folder."
else
  echo "[i] Create PHP info page."
  echo -e "<?PHP\nphpinfo ();\n?>" > /usr/share/webapps/index.php
  if [ $(grep -c '^hiawatha:' /etc/passwd) == 1 ]; then
    s6-envuidgid hiawatha s6-chown -U -- /usr/share/webapps/index.php
  fi
  if [ $(grep -c '^nginx:' /etc/passwd) == 1 ]; then
    s6-envuidgid nginx s6-chown -U -- /usr/share/webapps/index.php
  fi
fi

exit 0
