#!/usr/bin/with-contenv sh

set -e

if [ ! -d /etc/hiawatha/sites-enabled ]; then
  mkdir /etc/hiawatha/sites-enabled
  s6-envuidgid hiawatha s6-chown -U -- /etc/hiawatha/sites-enabled
fi

if test -e /etc/hiawatha/sites-enabled/*.site; then
  s6-echo "[i] Site(s) for Hiawatha found."
else
  s6-echo "[i] Create example site for Hiawatha."
  if [ -d /etc/php ]; then
    echo -e 'UrlToolkit {\n  ToolkitID = banshee\n  RequestURI isfile Return\n  Match ^/(css|files|images|js)/ Return\n  Match ^/(favicon.ico|robots.txt|sitemap.xml)$ Return\n  Match .*\?(.*) Rewrite /index.php?$1\n  Match .* Rewrite /index.php\n}\n\n' > /etc/hiawatha/sites-enabled/example.site
    echo -e 'VirtualHost {\n  Hostname = localhost\n  WebsiteRoot = /usr/share/webapps\n  StartFile = index.php\n  UseToolkit = banshee\n  ExecuteCGI = yes\n}\n' >> /etc/hiawatha/sites-enabled/example.site
  else
    echo -e 'VirtualHost {\n  Hostname = localhost\n  WebsiteRoot = /usr/share/webapps\n  StartFile = index.html\n}\n' > /etc/hiawatha/sites-enabled/example.site
  fi
  echo 'Include /etc/hiawatha/sites-enabled/' >> /etc/hiawatha/hiawatha.conf
  s6-envuidgid hiawatha s6-chown -U -- /etc/hiawatha/sites-enabled/example.site
  s6-chmod 675 /etc/hiawatha/sites-enabled/example.site
fi

exit 0
