version: '2.1'

services:
  traefik:
    restart: always
    container_name: traefik
    hostname: traefik
    image: maxder/alpine-traefik:x86_64
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080" # Webinterface
    volumes:
    - /srv/docker/traefik/tls:/etc/traefik/tls
    - /srv/docker/traefik/config:/etc/traefik/config
    - /var/run/docker.sock:/var/run/docker.sock
