#!/usr/bin/with-contenv sh

set -e

APPFOLDER=${APPFOLDER:-nextcloud}
APPDIR=/usr/share/webapps/${APPFOLDER}
APPDB=${APPDB:-nextcloud}
DBHOST=${DBHOST:-db}
DBUSER=${DBUSER:-$DB_ENV_DBUSER}
DBPASS=${DBPASS:-$DB_ENV_DBPASS}
APPADMIN=${APPADMIN:-admin}
APPADMINPASS=${APPADMINPASS:-admin}
INSTALL=${INSTALL:-silent}

if [ ${APPFOLDER} != "nextcloud" ]; then
  mv /usr/share/webapps/nextcloud /usr/share/webapps/${APPFOLDER}
  if [ -f /etc/nginx/sites-enabled/nextcloud.site ]; then
    s6-rmrf /etc/nginx/sites-enabled/nextcloud.site
  fi
  if [ -f /etc/nginx/sites-enabled/subfolder ]; then
    s6-rename /etc/nginx/sites-enabled/subfolder /etc/nginx/sites-enabled/nextcloud.site
    sed -i "s*nextcloud*${APPFOLDER}*g" /etc/nginx/sites-enabled/nextcloud.site
  fi
    sed -i "s*nextcloud*${APPFOLDER}*g" /etc/periodic/daily/nextcloud
    sed -i "s*nextcloud*${APPFOLDER}*g" /etc/periodic/15min/nextcloud
else
  s6-rmrf /etc/nginx/sites-enabled/subfolder
fi

if [ $INSTALL == "silent" ]; then
  until nc -z ${DBHOST} 3306; do sleep 1; echo "Waiting for DB to come up..."; done

  if ! mysql -u $DBUSER --password=$DBPASS -h $DBHOST -e "use ${APPDB}"; then
    echo -e "No database ${APPDB} found. Creating database now .."
    mysql -u $DBUSER --password=$DBPASS -h $DBHOST <<-EOF
    CREATE DATABASE IF NOT EXISTS ${APPDB} CHARACTER SET utf8;
    GRANT ALL PRIVILEGES ON ${APPDB}.* TO '$DBUSER'@'%' IDENTIFIED BY '$DBPASS';
    FLUSH PRIVILEGES;
EOF
  fi

  if [ ! -d /etc/nextcloud ]; then
    mkdir /etc/nextcloud
  fi

  s6-rmrf $APPDIR/config
  s6-ln -s /etc/nextcloud $APPDIR/config

  if [ ! -f $APPDIR/config/config.php ]; then
    echo -e  "<?php \n\$CONFIG = array (\n  'memcache.local' => '\\OC\\Memcache\\APCu',\n);\n" > $APPDIR/config/config.php
    chown nginx:www-data $APPDIR/config/config.php
    ping -c 3 redis > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo -e  "<?php \n\$CONFIG = array (\n  'memcache.local' => '\\OC\\Memcache\\APCu',\n);\n" > $APPDIR/config/config.php
else
      echo -e  "<?php \n\$CONFIG = array (\n  'memcache.local' => '\\OC\\Memcache\\APCu',\n'memcache.locking' => '\\OC\\Memcache\\Redis',\n'redis' =>array (\n    'host' => 'redis',\n    'port' => 6379,\n  ),\n);\n" > $APPDIR/config/config.php
    fi
    chown nginx:www-data $APPDIR/config/config.php
    echo -e "\n---\n[i] Installing Nextcloud via command line. Stay tuned!\n"
    s6-setuidgid nginx php $APPDIR/occ maintenance:install -nv --database \
    "mysql" --database-name "$APPDB"  \
    --database-user "$DBUSER" \
    --database-pass "$DBPASS" \
    --database-host "$DBHOST" \
    --admin-user "$APPADMIN" \
    --admin-pass "$APPADMINPASS" \
    --data-dir "/data"
    echo -e "\n[i] Login:\n Admin: $APPADMIN\n Pass: $APPADMINPASS\n---\n"
  fi
fi
rm /etc/cont-init.d/02-firstrun
echo -e "#!/usr/bin/with-contenv sh\ns6-setuidgid nginx php $APPDIR/occ upgrade\ns6-setuidgid nginx php $APPDIR/occ maintenance:mode --off\n\nexit 0" > /etc/cont-init.d/02-nextcloud_check_upgrade
chmod +x /etc/cont-init.d/02-nextcloud_check_upgrade

exit 0
